### ISSUE TITLE
[Bug] Documentation is not up to date

### ISSUE THREAD

**Issue by olivier-detilleux-sp** [sailpoint-oss/sailpoint-cli#108]
**Describe the bug** A clear and concise description of what the bug is.
Apparently, some cmd have changed with the recent CLI releases. There is no sail configure command anymore. To configure a PAT, it is required to use sail set pat ... The documentation is not updated with those changes.

**To Reproduce** Steps to reproduce the behavior:

1. Simply go to the readme or developer.sailpoint.com documentation. It is still explained that sail configure has to be executed to configure the authentication

**Expected behavior** A clear and concise description of what you expected to
happen.
Expected a documentation up to date with the CLI commands

**Actual behavior** A clear and concise description of what actually happens.
Doc not up to date

**Screenshots** If applicable, add screenshots to help explain your problem.

**Operating System (please complete the following information):**

- OS: MacOS 13.6
- CLI Environment 
- Version [2.0]

**Browser (please complete the following information):**

**Additional context** Add any other context about the problem here.

**Comment by luke-hagar-sp** [comment]
This was resolved in a prior doc update
