### ISSUE TITLE
[Bug] No Release Binaries for CLI v2.0.3

### ISSUE THREAD

**Issue by bedge-tamu** [sailpoint-oss/sailpoint-cli#118]
**Describe the bug** A clear and concise description of what the bug is.

It looks like there currently isn't any binaries attached to the v2.0.3 CLI release:
https://github.com/sailpoint-oss/sailpoint-cli/releases/tag/2.0.3
Since the sailpoint-cli formula has been updated in homebrew to 2.0.3, this results in a 404 when attempting to install.

**To Reproduce** Steps to reproduce the behavior:

No binaries listed under Releases for 2.0.3 as previous releases: https://github.com/sailpoint-oss/sailpoint-cli/releases/tag/2.0.3
Attempting to brew install `sailpoint-cli` fails with a 404:
```
brew tap sailpoint-oss/tap && brew install sailpoint-cli
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################################################################################################################################################################################################### 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
######################################################################################################################################################################################################################################################### 100.0%
==> Fetching sailpoint-oss/tap/sailpoint-cli
==> Downloading https://github.com/sailpoint-oss/sailpoint-cli/releases/download/2.0.3/sail_2.0.3_macOS_arm64.tar.gz
curl: (22) The requested URL returned error: 404

Error: sailpoint-cli: Failed to download resource "sailpoint-cli"
```

**Expected behavior** A clear and concise description of what you expected to
happen.

Binaries listed on release page, sailpoint-cli installation without error

**Actual behavior** A clear and concise description of what actually happens.
Only source code listed on release assets; 404 when installing `sailpoint-cli` via homebrew.

**Screenshots** If applicable, add screenshots to help explain your problem.
![image](https://github.com/sailpoint-oss/sailpoint-cli/assets/93270067/6dac5109-a83e-4651-8fdc-7fed83956d52)

**Operating System (please complete the following information):**

- OS: macOS 14.1.1
- CLI Environment: Terminal; zsh
- Version: 2.0.3

**Browser (please complete the following information):**

- Browser: Firefox
- Version 119.0.1

**Additional context** Add any other context about the problem here.

**Comment by tyler-mairose-sp** [comment]
Hello @bedge-tamu,

We had a temporary issue with one of our Github Actions causing the artifacts to be missing. We have resolved this and the release files for v2.0.3 are now available. https://github.com/sailpoint-oss/sailpoint-cli/releases/tag/2.0.3
