### ISSUE TITLE
[Bug] Search doesn't include nested attributes - without a template.

### ISSUE THREAD

**Issue by rob-buskens-sp** [sailpoint-oss/sailpoint-cli#119]
**Describe the bug**
Search command is not returning all attributes nested under attributes.
 
**To Reproduce**

1. replace the {Source Name} and {Attribute Name} placeholders and run the following sail command.
sail search query "attributes.interface:\"Attribute Sync\" AND attributes.sourceName:\"{Source Name}\" AND attributes.attributeName:\"{Attribute Name\"" --indices events

**Expected behavior** 
All nested attributes are returned (from a postman search)
```
[
    {
        "org": "none-sb",\
        "pod": "stg08-useast1",
        "created": "2023-11-18T03:18:35.447Z",
        "id": "4194f48a7c21780fc3f9bb60953d93b8e78b5fa167827656595f89d86bae050e",
        "action": "ModifyAccount",
        "type": "PROVISIONING",
        "actor": {
            "name": "System"
        },
        "target": {
            "name": "Homer Simpson"
        },
        "stack": "wps",
        "trackingNumber": "610441cb7b804d4f9c41454f1d23653e",
        "attributes": {
            "cloudAppName": "Source Name",
            "provisioningResult": "committed",
            "appId": "72b0c8c92c12483698627f1259c3ef3f",
            "accountUuid": "null",
            "operation": "Set",
            "previousValue": "IABCD",
            "sourceId": "source",
            "sourceName": "Source Name",
            "accountName": "IABCD",
            "interface": "Attribute Sync",
            "attributeName": "Attribute Name",
            "attributeValue": "ABCD"
        },
        "objects": [
            "ACCOUNT"
        ],
        "operation": "MODIFY",
        "status": "PASSED",
        "technicalName": "ACCOUNT_MODIFY_PASSED",
        "name": "Modify Account Passed",
        "synced": "2023-11-18T03:18:35.715Z",
        "_type": "event",
        "_version": "v7"
    }
]
```
**Actual behavior**
The following is the output and only attributes.sourceName is included:
```
{  
    "id": "fb7e2b4e8ea5ca50bc9f68afda42aa960a7f22fc90134befd56eff0ee3149e09",
    "name": "Modify Account Passed",
    "_type": "PROVISIONING",
    "created": "2023-11-13T15:43:35.250Z",
    "synced": "2023-11-13T15:43:35.432Z",
    "action": "ModifyAccount",
    "type": "",
    "actor": {
      "name": "System"
    },
    "target": {
      "name": "Homer Simpson"
    },
    "stack": "wps",
    "trackingNumber": "2b33986fc12a4afeb514814cb89a45b0",
    "ipAddress": "",
    "details": "",
    "attributes": {
      "sourceName": "Source Name"
    },
    "objects": [
      "ACCOUNT"
    ],
    "operation": "MODIFY",
    "status": "PASSED",
    "technicalName": "ACCOUNT_MODIFY_PASSED"
  }
```

**Screenshots** If applicable, add screenshots to help explain your problem.

**Operating System (please complete the following information):**

- OS: macOS Sonoma 14.1.1
- CLI Environment zsh, sail
- Version 2.0.3

**Browser (please complete the following information):**

- Browser: n/a
- Version: n/a

**Additional context**

Default API behaviour for search is to return nested attributes
Also tried using a search template which exhibited the same behaviour. Filing a separate bug for that.

**Comment by rob-buskens-sp** [comment]
The attributes are filtered to the ones defined here [Search Event](https://github.com/sailpoint-oss/sailpoint-cli/blob/156dd9085ac56488da1fc5620aec58b4e2c57576/internal/search/types.go#L159)

this worked... although I didn't do extensive testing with searches that don't provide these values. might not want a bunch of empty attributes that may not be applicable.

<img width="1357" alt="image" src="https://github.com/sailpoint-oss/sailpoint-cli/assets/105882429/8ff1bddc-65f5-4dea-9c9c-356a3bb3e287">

**Comment by tyler-mairose-sp** [comment]
Hey @rob-buskens-sp,

This is fixed in https://github.com/sailpoint-oss/sailpoint-cli/commit/ae6b3beb70d5543db9240e1ecf84205f0185cfda and will be included in the next release!
