### ISSUE TITLE
[Feature] option to list configured environments

### ISSUE THREAD

**Issue by rob-buskens-sp** [sailpoint-oss/sailpoint-cli#128]
You have to cat the config.yaml to know what environments are configured.

It would be nice if you could list the configured environments as a list.

I've seen similar list capabilities on aws console and others for all types.

**Comment by stephen-holinaty-sp** [comment]
+1 on this one - I would love to see a list of environments that I have configured, as i interact with Multiple tenants throughout my day

**Comment by tyler-mairose-sp** [comment]
Hey @rob-buskens-sp @stephen-holinaty-sp,

This will now be available with this latest commit: https://github.com/sailpoint-oss/sailpoint-cli/commit/862857cf707fd3b112292dcb8c982f820630d60e

We refactored the `environment` command and we believe it will a much better experience dealing with environments.

See full capabilities below:

# Environment                                                                
                                                                              
  Configure SailPoint IdentityNow environments for the CLI                    

Usage:
  sail environment [flags]
  sail environment [command]

Aliases:
  environment, env

Examples:

  ## Create a new environment                                                 
                                                                              
  You can add new environments by calling  create  and supplying a name that  
  does not already exist. The CLI will walk you through adding a new tenant   
  configuration.                                                              
                                                                              
    sail environment create {environment-name}                                
                                                                              
  If no environment is provided the CLI will use your tenant name as the name 
  of the environment.                                                         
                                                                              
    sail environment create                                                   
                                                                              
  ## Switching environments                                                   
                                                                              
  You can switch between environments by calling  use  and supplying the name 
  of an existing environment you want to switch to.                           
                                                                              
    sail environment use {environment-name}                                   
                                                                              
  ## Delete an environment                                                    
                                                                              
  You can delete an environment by calling  delete  and supplying the name of 
  an existing environment.                                                    
                                                                              
    sail environment delete {environment-name}                                
                                                                              
  If no environment is provided this command will delete the active           
  environment.                                                                
                                                                              
    sail environment delete                                                   
                                                                              
  ## Update an environment                                                    
                                                                              
  You can update an environment by calling  update  and supplying the name of 
  an existing environment.                                                    
                                                                              
    sail environment update {environment-name}                                
                                                                              
  If no environment is provided this command will delete the active           
  environment.                                                                
                                                                              
    sail environment update                                                   
                                                                              
  ## View an environment                                                      
                                                                              
  You can print an environment by calling  show  supplying the name of an     
  existing environment.                                                       
                                                                              
    sail environment show {environment-name}                                  
                                                                              
  If no environment is provided this command will show the active environment.
                                                                              
    sail environment show                                                     



Available Commands:
  create      Create a new environment in the CLI
  delete      Delete the active environment in the CLI
  list        List all configured environments in the CLI
  show        View an environment in the CLI
  update      Update an existing environment in the CLI
  use         Set an environment as the active environment in the CLI

Flags:
  -h, --help   help for environment

Global Flags:
      --debug        Enable debug logging
      --env string   Environment to use for SailPoint CLI commands

Use "sail environment [command] --help" for more information about a command.
