### ISSUE TITLE
[Bug] OSX keyring storage of client ID and client Secret stores incorrect values

### ISSUE THREAD

**Issue by rob-buskens-sp** [sailpoint-oss/sailpoint-cli#129]
On OSX, setting an environment client ID / Secret in the keyring stores incorrect value:

**To Reproduce**
1. sail set pat
2. enter clientId
3. enter clientSecret
4. Open keychain access
5. search env, pick the one for the current enviornment
6. click show password
The value is "go-keyring-"
![image](https://github.com/sailpoint-oss/sailpoint-cli/assets/105882429/1448fdcb-1f00-4173-90d2-f1222ba4d0ed)

**Expected behavior**
A value representing the stored item.

**Actual behavior**
"go-keyring-"

**Operating System**

- OS: Mac OS Sonoma
- CLI Environment: zsh
- Version:  14.2.1 (23C71)

**Additional context**
sail version 2.0.3

**Comment by jordan-violet-sp** [comment]
This issue has been mentioned on **SailPoint Developer Community Forum**. There might be relevant details there:

https://developer.sailpoint.com/discuss/t/sailpoint-cli-credentials-issue/39820/1

**Comment by rob-buskens-sp** [comment]
in my experience it happens only if you copy and paste the secret into a terminal window when the CLI prompts for input.

sail set pat
Personal Access Token Client ID:{paste client id}
etc.

whereas if you copy and paste the client id and client secret as command line parameters, it works.

sail set pat -i {ClientId} -s {ClientSecret}

**Comment by tyler-mairose-sp** [comment]
Hey @rob-buskens-sp,

This was fixed in the following release https://github.com/sailpoint-oss/sailpoint-cli/releases/tag/2.1.5.

Please re-open if you still find this to be a problem after this release version!
