### ISSUE TITLE
[Bug] sail rule download or sail rule download --cloud is not working 

### ISSUE THREAD

**Issue by Mehulkumar-Chavda** [sailpoint-oss/sailpoint-cli#146]
sail rule download is not working 

sail rule download --connector (This is working)
sail rule download --cloud (This is not working, Throwing error, Please find the error below)

% sail rule download --cloud
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/sailpoint-oss/sailpoint-cli/cmd/rule.saveCloudXMLRules(0xc0005fa100, {0x27871bd, 0x20}, {0xc0001ade90, 0x1, 0x1}, {0x0, 0x0, 0x0}, 0x0, ...)
	/home/runner/work/sailpoint-cli/sailpoint-cli/cmd/rule/download.go:157 +0x18f4
github.com/sailpoint-oss/sailpoint-cli/cmd/rule.newDownloadCommand.func1(0xc0002eb600?, {0xc0001acbe0?, 0x4?, 0x27143e0?})
	/home/runner/work/sailpoint-cli/sailpoint-cli/cmd/rule/download.go:95 +0x237
github.com/spf13/cobra.(*Command).execute(0xc000000600, {0xc0001acbc0, 0x1, 0x1})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x87c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000004900)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
	/home/runner/work/sailpoint-cli/sailpoint-cli/main.go:26 +0x1a

**Comment by tyler-mairose-sp** [comment]
Hey @Mehulkumar-Chavda,

Could you provide me the json output from calling the APIs below for the tenant that is failing?

POST `/beta/sp-config/export` with the following body:

```json
{
  "description": "Export Rules",
  "includeTypes": [
    "RULE"
  ],
  "objectOptions": {
  }
}
```

Then calling GET `beta/sp-config/export/{jobId}/download`

If there is sensitive data inside the rule response, feel free to send me the output directly. https://developer.sailpoint.com/discuss/new-message?username=tyler_mairose

This will help me narrow down the data that is causing the deserialization to fail.

**Comment by justinhaines** [comment]
I am having the same error on one specific tenant. I'll send you the file of my export now...

**Comment by Mehulkumar-Chavda** [comment]
Hi Tyler,

Please find the output in the attached file

Thank you,
Mehul

From: Tyler Mairose ***@***.***>
Date: Wednesday, May 15, 2024 at 9:45 AM
To: sailpoint-oss/sailpoint-cli ***@***.***>
Cc: Chavda, Mehul ***@***.***>, Mention ***@***.***>
Subject: Re: [sailpoint-oss/sailpoint-cli] [Bug] sail rule download or sail rule download --cloud is not working (Issue #146)

Hey @Mehulkumar-Chavda<https://urldefense.com/v3/__https:/github.com/Mehulkumar-Chavda__;!!Ivohdkk!jFM_64zL0d3sVsGEZg_RjIRFlpPIqKcg4GW-q937pBB5BxYMaUASPcFlkDOj-tHe5ChlwJyguWa6aU1ysLI-4uaM2oBv3tE$>,

Could you provide me the json output from calling the APIs below for the tenant that is failing?

POST /beta/sp-config/export with the following body:

{

  "description": "Export Rules",

  "includeTypes": [

    "RULE"

  ],

  "objectOptions": {

  }

}

Then calling GET beta/sp-config/export/{jobId}/download

If there is sensitive data inside the rule response, feel free to send me the output directly. https://developer.sailpoint.com/discuss/new-message?username=tyler_mairose<https://urldefense.com/v3/__https:/developer.sailpoint.com/discuss/new-message?username=tyler_mairose__;!!Ivohdkk!jFM_64zL0d3sVsGEZg_RjIRFlpPIqKcg4GW-q937pBB5BxYMaUASPcFlkDOj-tHe5ChlwJyguWa6aU1ysLI-4uaMawZyMnk$>

This will help me narrow down the data that is causing the deserialization to fail.

**Comment by Mehulkumar-Chavda** [comment]
@tyler-mairose-sp SailPoint CLI still not working 
I am keep getting below error when try to download rules 

sail rule download
2024/07/30 17:44:12 INFO Job Complete
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/sailpoint-oss/sailpoint-cli/cmd/rule.saveCloudXMLRules(0xc0004376c0, {0x2787c3e, 0x20}, {0xc0000442e0, 0x1, 0x1}, {0x0, 0x0, 0x0}, 0x0, ...)
	/home/runner/work/sailpoint-cli/sailpoint-cli/cmd/rule/download.go:157 +0x18f4
github.com/sailpoint-oss/sailpoint-cli/cmd/rule.newDownloadCommand.func1(0xc00036f600?, {0x3734300?, 0x4?, 0x2714e62?})
	/home/runner/work/sailpoint-cli/sailpoint-cli/cmd/rule/download.go:99 +0x1b4
github.com/spf13/cobra.(*Command).execute(0xc000002600, {0x3734300, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x87c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000300600)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
	/home/runner/work/sailpoint-cli/sailpoint-cli/main.go:26 +0x1a
	
Can someone please help os there any other way to download / view cloud rule after /CC API is discontinued ?
Or can someone please help to resolve above issue 

Thank you

**Comment by antonypetson** [comment]
> Hey @Mehulkumar-Chavda,
> 
> Could you provide me the json output from calling the APIs below for the tenant that is failing?
> 
> POST `/beta/sp-config/export` with the following body:
> 
> ```json
> {
>   "description": "Export Rules",
>   "includeTypes": [
>     "RULE"
>   ],
>   "objectOptions": {
>   }
> }
> ```
> 
> Then calling GET `beta/sp-config/export/{jobId}/download`
> 
> If there is sensitive data inside the rule response, feel free to send me the output directly. https://developer.sailpoint.com/discuss/new-message?username=tyler_mairose
> 
> This will help me narrow down the data that is causing the deserialization to fail.

I am getting response through sp-config via Postman but CLI is failing to download.

`sail rule download -c
2024/08/03 18:39:14 INFO Job Complete
panic: interface conversion: interface {} is nil, not string
`

sail -v
sail version 2.1.4

**Comment by Mehulkumar-Chavda** [comment]
Hi @tyler-mairose-sp  and @antonypetson 

Same with me I can execute sp-config via postman but sailpoint CLI is giving me error when try to download error 

2024/08/20 12:04:51 INFO Job Complete
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/sailpoint-oss/sailpoint-cli/cmd/rule.saveCloudXMLRules(0xc0004de240, {0x1ba53dc, 0x20}, {0xc000668d40, 0x1, 0x1}, {0x0, 0x0, 0x0}, 0x0, ...)
        /home/runner/work/sailpoint-cli/sailpoint-cli/cmd/rule/download.go:157 +0x18f4
github.com/sailpoint-oss/sailpoint-cli/cmd/rule.newDownloadCommand.func1(0xc0002e5600?, {0x2b8d9c0?, 0x4?, 0x1b2fab8?})
        /home/runner/work/sailpoint-cli/sailpoint-cli/cmd/rule/download.go:99 +0x1b4
github.com/spf13/cobra.(*Command).execute(0xc0001a8900, {0x2b8d9c0, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x87c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000570600)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
        /home/runner/work/sailpoint-cli/sailpoint-cli/main.go:26 +0x1a
        
@tyler-mairose-sp I already provide the output you requested earlier will this ever resolve?

Thank you

**Comment by tyler-mairose-sp** [comment]
@Mehulkumar-Chavda I apologize, I never received the output you provided. I messaged you directly on our developer community forum, would you be able to send it to me there?

**Comment by Mehulkumar-Chavda** [comment]
Hi @tyler-mairose-sp I cannot able to send the message on "https://developer.sailpoint.com/discuss/latest"

Sending you file here 

[Get-sp-config-exportJobId.json](https://github.com/user-attachments/files/16851201/Get-sp-config-exportJobId.json)
[Post-export.json](https://github.com/user-attachments/files/16851203/Post-export.json)

**Comment by tyler-mairose-sp** [comment]
@Mehulkumar-Chavda, Thank you for providing this. I believe I have the issue figured out. I will post back here when I have a new release ready.

**Comment by tyler-mairose-sp** [comment]
@Mehulkumar-Chavda @antonypetson @justinhaines 

This is fixed with https://github.com/sailpoint-oss/sailpoint-cli/commit/3078c2f268e744bd605dfe4b7fae44ebc97e8a2f and will be included in the next release!
