### ISSUE TITLE
[Bug] env not switching when called

### ISSUE THREAD

**Issue by mpotti** [sailpoint-oss/sailpoint-cli#152]
I currently have 2 environments set up. One for Sandbox and one for Prod. 
If you need to see the non removed sensitive data logs please let me know I can email you the information. 

environments configured:

`
PS C:\Users\REMOVED > sail environment list
{
  "default": {
    "baseurl": "REMOVED",
    "tenanturl": "REMOVED"
  },
  "prod": {
    "baseurl": "REMOVED",
    "tenanturl": "REMOVED"
  },
  "sandbox": {
    "baseurl": "REMOVED",
    "tenanturl": "REMOVED"
  }
}`

Rules list debug log: even though I called sandbox it is still passing the prod configuration. 

PS C:\Users\REMOVED> sail rule list -c --debug --env sandbox
2024/06/13 12:04:32 DEBU <config/config.go:199> Token Debug Info user_name=REMOVED org=REMOVED pod=REMOVED
2024/06/13 12:04:32 DEBU <go-retryablehttp@v0.7.5/client.go:614> [DEBUG] POST https://REMOVED.api.identitynow.com/beta/sp-config/export
2024/06/13 12:04:34 DEBU <go-retryablehttp@v0.7.5/client.go:614> [DEBUG] GET https://REMOVED.api.identitynow.com/beta/sp-config/export/REMOVED
2024/06/13 12:04:34 INFO <rule/list.go:76> Job Complete
2024/06/13 12:04:34 DEBU <go-retryablehttp@v0.7.5/client.go:614> [DEBUG] GET https://REMOVED.api.identitynow.com/beta/sp-config/export/REMOVED/download

PS C:\Users\REMOVED> sail rule list -c --debug --env prod
2024/06/13 12:04:32 DEBU <config/config.go:199> Token Debug Info user_name=REMOVED org=REMOVED pod=REMOVED
2024/06/13 12:04:32 DEBU <go-retryablehttp@v0.7.5/client.go:614> [DEBUG] POST https://REMOVED.api.identitynow.com/beta/sp-config/export
2024/06/13 12:04:34 DEBU <go-retryablehttp@v0.7.5/client.go:614> [DEBUG] GET https://REMOVED.api.identitynow.com/beta/sp-config/export/REMOVED
2024/06/13 12:04:34 INFO <rule/list.go:76> Job Complete
2024/06/13 12:04:34 DEBU <go-retryablehttp@v0.7.5/client.go:614> [DEBUG] GET https://REMOVED.api.identitynow.com/beta/sp-config/export/REMOVED/download

**Comment by tyler-mairose-sp** [comment]
Hey @mpotti,

Do you have any environment variables set for the CLI? It will default to those first.
