### ISSUE TITLE
Search Error - Got uncovertable type '[]interface ()

### ISSUE THREAD

**Issue by justinhaines** [sailpoint-oss/sailpoint-cli#153]
**Describe the bug** A clear and concise description of what the bug is.
Search query returns error shown in screenshot. It appears this search result has more than one source with errors but I cannot find any other details related to error

**To Reproduce** Steps to reproduce the behavior:
search query "(status:Incomplete AND sources:Epic)" --indices accountactivities -f "C:\Users\justin.haines\OneDrive - Optiv Security Inc\WakeMed\HealthCheck"

**Expected behavior** Return search results.

**Actual behavior** A clear and concise description of what actually happens.
Error occurs

**Screenshots** If applicable, add screenshots to help explain your problem.
![image](https://github.com/user-attachments/assets/744766f9-650f-4f81-9c3a-d7e740079111)

- OS: Windows 10

**Comment by tyler-mairose-sp** [comment]
Hey @justinhaines,

This is fixed by https://github.com/sailpoint-oss/sailpoint-cli/commit/b6d847fecbf40404b1531dfc7a44281767a2cc84 and will be included with the next release!
