### ISSUE TITLE
[BUG] Getting 404 error when uploading connector

### ISSUE THREAD

**Issue by colin-mckibben-sp** [sailpoint-oss/sailpoint-cli#24]
**Describe the bug** A clear and concise description of what the bug is.

When using `sail conn upload -c test-conn-1 -f dist\test-conn-1-0.1.0.zip`, the following error is encountered:

```
POST /beta/platform-connectors/test-conn-1/versions HTTP/1.1
...
HTTP/2.0 404 Not Found
```

However, the command `sail conn list` works.

**To Reproduce** Steps to reproduce the behavior:

Create a new connector using the CLI and attempt to upload it to your tenant.

**Expected behavior** A clear and concise description of what you expected to
happen.

The command should succeed, and the connector should be uploaded to my IDN tenant.

**Actual behavior** A clear and concise description of what actually happens.

The command fails with a 404 not found error.

**Screenshots** If applicable, add screenshots to help explain your problem.

**Operating System (please complete the following information):**

- OS: [e.g. Windows 10 19044.1889, Ubuntu 18.04, Mac OS Monterey 12.4]
- CLI Environment [e.g. Command Prompt, Powershell, Terminal]
- Version [e.g. 1.04]

**Additional context** Add any other context about the problem here.

**Comment by PiotrTraczynski** [comment]
It is ok. I did not created connector before upload. sorry

**Comment by ashley-george-sp** [comment]
Resolved as the connector was not created. Confirmed with Piotr
