### ISSUE TITLE
[Bug] HTTP DELETE Method disallowed

### ISSUE THREAD

**Issue by mattsuid** [sailpoint-oss/sailpoint-cli#29]
**Describe the bug** I am unable to delete connectors that I have created in my sandbox tenant.

**To Reproduce** Steps to reproduce the behavior:

1. Create and upload a template to a sandbox tenant.
2. Attempt the `sail conn delete --id xxxxx` or `sail conn delete -c xxxxx` commands to delete a connector

**Expected behavior** When executing the command I would expect it to delete the connector and return a success response.

**Actual behavior** When executing the command it is indicating that there is an HTTP 405 error from the SaaS environment.

**Screenshots**
![Screenshot 2023-01-11 at 12 13 39 PM](https://user-images.githubusercontent.com/17863645/211885546-8191d746-df0f-4640-b385-d965ed7f346e.png)

**Operating System (please complete the following information):**

- OS: MacOs Ventura 13.1
- CLI Environment: zsh
- Version: 0.4.0

**Additional context** I haven't tested this in a prod tenant, but have tried it from multiple networks.

**Comment by luke-hagar-sp** [comment]
Hey @mattsuid,

Thanks for opening this issue! 
I'll look into this and get back to you with more information.

It's likely either an issue with our formatting, or something in documentation that needs to be corrected.

**Comment by mattsuid** [comment]
Just snooped around a little and wanted to add some debug logs. Looks like I is issuing an HTTP DELETE method, which seems appropriate. Here are some redacted logs in case the context is helpful.


![Screenshot 2023-01-25 at 8 41 08 AM](https://user-images.githubusercontent.com/17863645/214593309-3b6681f6-1a47-40e8-a820-0886cafdaef8.png)

**Comment by colin-mckibben-sp** [comment]
Thanks @mattsuid.  I forwarded this to our connectivity team.  They will look into it and provide a response soon.

**Comment by colin-mckibben-sp** [comment]
Released in version 0.4.1

https://github.com/sailpoint-oss/sailpoint-cli/releases/tag/0.4.1

**Comment by mattsuid** [comment]
Updated to 0.4.1 and confirmed this is working for me as well
