### ISSUE TITLE
[Bug] No go file present in the directory

### ISSUE THREAD

**Issue by Swapnasarit-Panda** [sailpoint-oss/sailpoint-cli#32]
I am unable to execute sail.exe with go build command as mentioned in the document.
It is saying no go file present in the directory. I also tried go mod and go init but nothing helps.

<img width="443" alt="go build" src="https://user-images.githubusercontent.com/115689195/217150585-2e732ade-ca36-48ba-b2f2-3de4081a4bdb.png">

**Comment by luke-hagar-sp** [comment]
Hey @Swapnasarit-Panda,

I see you closed this Issue, I hope you were able to get it sorted out.

If you have any other issues please let us know!
