### ISSUE TITLE
misspelling indices in search

### ISSUE THREAD

**Issue by dt1ll0ts0n** [sailpoint-oss/sailpoint-cli#46]
I noticed that the word 'indicies' is being used in your search code. I believe the plural of index has only one 'i.'
indices

**Comment by luke-hagar-sp** [comment]
@dt1ll0ts0n Thank you for this!

This was also brought to our attention during the developer days conference, and has been resolved in a recent PR. 

I encourage you to submit more tickets like this if you see any other spelling errors in the future, or if you have absolutely any other ideas or feedback to provide.

Thank you for being a great part of our incredible community!
