### ISSUE TITLE
[Bug] spconfig export --include WORKFLOWS fails without details

### ISSUE THREAD

**Issue by rob-buskens-sp** [sailpoint-oss/sailpoint-cli#97]
using v1.2 of the CLI, running:
sail spconfig export --include WORKFLOWS

and then checking the status with:
sail spconfig status --export <id>

results in the following which doesn't have details on what the error is

Job Type: EXPORT
Job ID: 517b1476-cd1a-44be-a8a3-d9537b13ea92
Status: FAILED
Expired: 2023-09-15 17:41:00 +0000 UTC
Created: 2023-09-08 17:41:00.777 +0000 UTC
Modified: 2023-09-08 17:41:00.902 +0000 UTC
Completed: 0001-01-01 00:00:00 +0000 UTC

Getting the status via API shows the error information in more detail:
{
    "jobId": "517b1476-cd1a-44be-a8a3-d9537b13ea92",
    "status": "FAILED",
    "type": "EXPORT",
    "message": "java.lang.IllegalArgumentException: Supplied types are not supported: [WORKFLOWS]",
    "expiration": "2023-09-15T17:41:00Z",
    "created": "2023-09-08T17:41:00.777Z",
    "modified": "2023-09-08T17:41:00.902Z"
}

**To Reproduce** Steps to reproduce the behavior:

sail spconfig export --include WORKFLOWS
sail spconfig status --export <id from previous>

**Expected behavior**
The output would included the error message as shown in the API status response

**Actual behavior**
No detail provided

**Screenshots**
n/a

**Operating System (please complete the following information):**

- OS: Mac OS Ventura 13.5.2
- CLI Environment: terminal zsh
- Version: 1.2

**Browser (please complete the following information):**

- Browser: n/a
- Version: n/a

**Additional context** Add any other context about the problem here.
The api doc here https://developer.sailpoint.com/idn/api/beta/export-sp-config has WORKFLOWS

**Comment by rob-buskens-sp** [comment]
I did some more digging. in postman using the spconfig apis directly, workflows export if you do NOT provide an includeTypes list.

`{
  "includeTypes": [
   ]
}`

The downloaded file includes workflows.

but:

`{
  "includeTypes": [
      "WORKFLOWS"
   ]
}`

fails with:
{
    "jobId": "eae4ea66-d930-4ad4-9179-4fb2c06f40d3",
    "status": "FAILED",
    "type": "EXPORT",
    "message": "java.lang.IllegalArgumentException: Supplied types are not supported: [WORKFLOWS]",
    "expiration": "2023-09-15T20:50:55Z",
    "created": "2023-09-08T20:50:55.961Z",
    "modified": "2023-09-08T20:50:56.143Z"
}

**Comment by lori-vangulick-sp** [comment]
The correct value is "WORKFLOW" singular. Documentation needs to be updated to reflect that.

**Comment by jordan-violet-sp** [comment]
This has been referenced in the 2.0 release of the CLI.  Please resubmit if this is still an issue using v2.0.
