### ISSUE TITLE
[Bug] Self attribute not included on SPConfig export 

### ISSUE THREAD

**Issue by ghost** [sailpoint-oss/sailpoint-cli#99]
Running `sail spconfig export -i FORM_DEFINITION -w`

Output does not contain a valid `self` property for the object being exported, this is likely an issue with the API Spec or generated SDK types

Currently returned:
```
"self": {},
```

Should be:
```
"self": {
        "id": "a4d89a70846b4c9ba573b6be1871ab93",
        "name": "Name of Object",
        "type": "Type of Object"
 }, 
```

**Comment by jordan-violet-sp** [comment]
@luke-hagar-sp - can you update your original submission to be more descript?

**Comment by tyler-mairose-sp** [comment]
This is fixed with https://github.com/sailpoint-oss/sailpoint-cli/commit/3f4ab1021fd4d01840fa60f0a05e55a8688199c3 the golang-sdk dependency was updated to the latest version which includes the `self` property on spconfig export objects.
